project:
  type: website

website:
  title: Project Title
  navbar:
    right:
      - icon: github
        href: https://github.com/MattOsterhoudt/final-project-osterhoudt # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: https://docs.google.com/presentation/d/1TZ_ulpWaw1n-8P9s7xOuummwijjVyKmHYBy4E-_B7mY/edit?usp=sharing
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
  warning: false
  message: false
