---
title: "Stock Market Analysis"
subtitle: "Proposal"
author: 
  - name: "Matt Osterhoudt"
    affiliations:
      - name: "College of Information Science, University of Arizona"
description: "To be filled"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
import yfinance as yf
```

## Dataset

```{python}
#| label: load-dataset
#| message: false

# S&P 500 Index Stock
ticker1 = yf.Ticker("INX")
data1 = ticker1.history(period = "max")
print(data1.to_string())

# Schwab Index Stock
ticker2 = yf.Ticker("SWPPX")
data2 = ticker2.history(period = "max")
print(data2.to_string())

# Microsoft Stock. I wanted to include a consistent large cap stock
ticker3 = yf.Ticker("MSFT")
data3 = ticker3.history(period = "max")
print(data3.to_string())
```

I have not fully decided which stock indexes, ETFs, or Large cap data to work with yet, but above is a start. The code shown retrieves the stock data using the yfinance package, which helps retrieves Yahoo stock data. I plan to implement a cleaner csv format for the stock data later, but the only columns I would be taking are the date, opening price, closing price, and daily high/low. I plan to range the data from the year 2000-2023, and then use the models to predict 2024 prices. 

## Goal

-   The high-level goal for this project will be to implement a successful ARIMA, LSTM, and Prophet model to predict stock prices, and to determine which model performs the best.

## Goal Description & Motivation

-   In order to meet this goal, I plan to analyze at least 3 different stocks. So far, I plan to use indexes such as the S&P 500 and Schwab, which have been around for quite a while. I also plan to see if using a consistent, large cap stock such as Microsoft yields any predictive patterns. The three models I will be utilizing for this project is the ARIMA (Autoregressive Integrated Moving Average), LSTM (Long Short-Term Memory), and Prophet (Meta's time series forecasting model). I will explain the strengths/weaknesses of each in my write-up.
-   My motivation is simply that I find stocks fascinating. I think it would be neat to test predictive models to see if there is any basis for quality stock prediction. I don't expect that my models will provide anything revolutionary; there are far better models out there that also utilize a lot more variables. Rather, I want to correctly implement the models and determine which model is the most effective. I hypothesize that large cap stocks like MSFT will have higher predictability with LSTM, whereas indexes that follow a more linear and season trend will have higher predictability with ARIMA.

## Analysis plan

-   I plan to use stock data from 2000-2023, and predict the 2024 stock prices with the 3 models. Then, I will directly compare the predicted 2024 prices with the actual 2024 prices, and examine how well each model did with predictability. If necessary, I will also implement cross-validation to measure the effectiveness of each model, while interpreting the results of the best performing model.
